### ISSUE TITLE
Table 'msyn_helium7.joo4_virtuemart_products_en_gb' doesn't exist

### ISSUE THREAD

**Issue by cat1910** [Dudebaker/Virtuemart-Finder#2]
Hi,

I tried your plugin on Joomla 4 / Virtuemart 4, version 1.0.1.

My website is in French.
When I try to index content in the smart search component,I get this issue :
Table 'msyn_helium7.joo4_virtuemart_products_en_gb' doesn't exist

Can you help ?
Regards,
Catherine

**Comment by Dudebaker** [comment]
Hi,

how does your language configuration in Virtuemart look alike?

Only if there's no default language the script falls back to en-gb.
Maybe you do not have set the default and or the additional languages correctly?
Please go into the Virtuemart configuration and set both to french and save.

If this does not work, add english to the additional languages, then Virtuemart creates automatically the en-gb tables.
After that, you can remove english from the configuration, the tables will stay in place.


Greetings

**Comment by cat1910** [comment]
Hi,

yes right, it's working better, thank you !

Now I have a problem with categories containing the character (and maybe some other special characters)  : '

When indexing content in smart search component, I get this message : "JSON.parse: unexpected character at line 1 column 1 of the JSON data"

Regards,
Catherine

**Comment by Dudebaker** [comment]
That's a hard one - maybe try to enabled system-debugging in the global configuration.
Then you should see more then this error.
Then you should also see a new option "Debug indexing" or some thing similar, with this you could enter a specific virtuemart-id to check if it has something to do with this character, then you would have to remove or exchange this character.

If you cannot solve this with these steps, I would need a copy of the categories-tables to do some deeper debugging.

**Comment by Dudebaker** [comment]
I've tested now multiple (more or less all which I have on my keyboard) special characters in Name, Alias, Meta-Fields or Description of a category.
All are working properly without any errors:

^ ° ! " § $ % & / ( ) = ? ` ´ ² ³ { [ ] } \ @ € + # , . - < * ' _ : ; > ~ | á é ó ú

So I would have exactly to know which character forces this error.

**Comment by cat1910** [comment]
The problem appears with the categories. Only the 11 first are indexed. But I can't see what is the problem with the next ones.
Where can I send you the table ?
Regards,
Catherine

**Comment by Dudebaker** [comment]
you can attach them here or send me a pm or add a link to pastebin or something similar

**Comment by cat1910** [comment]
[joo4_virtuemart_categories_fr_fr.txt](https://github.com/user-attachments/files/16915241/joo4_virtuemart_categories_fr_fr.txt)
Here is the file of the virtuemart categories table. I really don't see where is the problem, hope you will find it !

**Comment by Dudebaker** [comment]
I can index them (11 till 22) without any issues, so it has nothing to do with any characters:
![image](https://github.com/user-attachments/assets/96c41442-7a40-4bd6-82c8-1afc92e29b8f)

You have now two options:
- Install Joomla 5 and use there the Index debugging feature to find the entry with the issues as mentioned before
![image](https://github.com/user-attachments/assets/aa48c79c-8f34-49af-901d-771edcd28889)
- Or give me a whole backup of all tables (at least all virtuemart-category-tables and the virtuemart-media-table). Only with this I can check the whole category tree

For your info - I'm now at least two weeks on vacation and will not really have time to answer tickets.

**Comment by Dudebaker** [comment]
I had a customer with many french words (accents above letter, ex. é).
In this installation I found the issue and I couldn't index the whole shop.

The issue is not in my plugins, it had something to do with the database structure of the finder-tables.
The following table-columns had to be set to the ut8mb4_bin collation (like it is with a fresh j5 installation), in my case these were instead set to utf8mb4_general_ci.

- #_finder_terms.term
- #_finder_terms.stem
- #_finder_terms.soundex
- #_finder_terms_common.term
- #_finder_tokens.term
- #_finder_tokens.stem
- #_finder_tokens_aggregate.term
- #_finder_tokens_aggregate.stem

Please check your database structure and change it accordingly.
And please give me response if it worked or not.


This installation was migrated through multiple Joomla version.
A short check reveals that J3 had this column not set to any specific character set.
Joomla 4 changed that, but the whole com_finder component does not have and update-script so the database was never modified to this state.

**Comment by Dudebaker** [comment]
Since there is no response I close this issue.
